# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3e3e251e919a3c054b2de2be8bd180fcc7958351874cf61bd58d5bf719506f82e2826fdbffbd041791ba7942fe75cfa7d3425fa8a40ba8c53db42f14b62645

test:
  secret_key_base: 4b8ad876b6abd136ba2535fb98f1b078892ba7fc48d6efef34c93db1fcb1fa883b05cc4a1efa63c96405d63175157ffd8befbc4f140301fda205ce305ead6957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
